# Generated by Django 3.2.3 on 2021-07-03 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addnote',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=500)),
                ('cat', models.CharField(choices=[('1', 'Developer'), ('2', 'ManualTesting'), ('3', 'AutomationTesting'), ('4', 'AI'), ('5', 'HardwareComputer'), ('6', 'NewTechnology')], max_length=1)),
                ('Author', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=255)),
                ('L_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=500)),
                ('document_img', models.ImageField(upload_to='add_images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='impotantImage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=500)),
                ('document_img', models.ImageField(upload_to='add_images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('Decri', models.CharField(max_length=255)),
                ('p_url', models.CharField(max_length=255)),
                ('Img', models.ImageField(upload_to='add_images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
