# Generated by Django 3.2.3 on 2021-08-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technico_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Img',
            field=models.FileField(upload_to='add_images'),
        ),
    ]
