# Generated by Django 3.2.3 on 2021-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technico_app', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
